name: ML Model Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r day5/requirements.txt
    
    - name: Create necessary directories
      run: |
        mkdir -p day5/演習1/data
        mkdir -p day5/演習1/models
        mkdir -p day5/演習1/mlruns
    
    - name: Generate test data and train model
      run: |
        cd day5/演習1
        python generate_test_data.py
        python train_model.py
        ls -la data/
        ls -la models/
    
    - name: Run tests
      run: |
        cd day5/演習1
        python -m pytest tests/test_model.py -v 