name: ML Model Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: day5/演習1

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas numpy
    
    - name: Check directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Tests directory contents:"
        ls -la tests/
        echo "Models directory contents:"
        ls -la models/
        echo "Data directory contents:"
        ls -la data/
    
    - name: Generate test data
      run: |
        echo "Generating test data..."
        python generate_test_data.py
        echo "Test data generated. Contents of data directory:"
        ls -la data/
    
    - name: Train model
      run: |
        echo "Training model..."
        python train_model.py
        echo "Model trained. Contents of models directory:"
        ls -la models/
    
    - name: Run model tests
      run: |
        echo "Running model tests..."
        python -m unittest discover -s tests -v
        echo "Tests completed."
    
    - name: Check test results
      if: always()
      run: |
        echo "Test execution completed. Checking results..."
        if [ -f "test_results.txt" ]; then
          cat test_results.txt
        fi 